name: Invoke Lambda Function

on:
  push:
    branches:
      - main

jobs:
  invoke_lambda:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-northeast-1
      - name: Invoke Lambda Function-Purchase
        run: |
          aws lambda invoke --function-name CopyChecker-Flyway --cli-binary-format raw-in-base64-out --payload \"MIGRATE\" output.txt